{% set name = "multiscale-spatial-image" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multiscale_spatial_image-{{ version }}.tar.gz
  sha256: 07db47c3358bdfad9688a5ee8064a219ec72a43deb65e30bd4e591adfe35d10f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.8
  run:
    - dask-core
    - dask-image
    # - itk-filtering >=5.3.0  # Optional dependency
    - numpy
    - python >=3.8
    - spatial-image >=0.2.1
    - xarray
    - xarray-datatree >=0.0.5
    - zarr  # Used but not declared

test:
  imports:
    - multiscale_spatial_image
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/multiscale-spatial-image
  summary: Generate a multiscale, chunked, multi-dimensional spatial image data structure that can be serialized to OME-NGFF.
  dev_url: https://github.com/spatial-image/multiscale-spatial-image
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
